- CHANGELOG.md
- core/aws_requester.py
- core/http/basic_authentication.py
- core/requester.py
- core/util/file_util.py
- core/web3/eth_client.py
> Feature: Add BasicAuthentication + add post_form to Requester

- CHANGELOG.md
- core/api/health.py
- core/api/kiba_route.py
- core/aws_requester.py
- core/exceptions.py
- core/http/basic_authentication.py
- core/queues/message_queue_processor.py
- core/queues/model.py
- core/queues/sqs_message_queue.py
- core/requester.py
- core/s3_manager.py
- core/service_client.py
- core/slack_client.py
- core/store/retriever.py
- core/store/saver.py
- core/util/dict_util.py
- core/util/file_util.py
- core/util/hashing_util.py
- core/util/list_util.py
- core/util/typing_util.py
- core/web3/eth_client.py
- requirements-dev.txt
- requirements.txt
- setup.py
> Feature: deprecate Message._COMMAND in favour of Message.COMMAND + update dependencies

- CHANGELOG.md
- core/queues/model.py
> Fix: update queue Message to resume using _COMMAND because of pydantic limit

- CHANGELOG.md
- core/api/kiba_route.py
- core/exceptions.py
- core/util/chain_util.py
> Feature: add redirect exceptions

- CHANGELOG.md
- core/queues/message_queue_processor.py
> Feature: add batch and non-run processor to MessageQueueProcessor

- core/queues/message_queue_processor.py
> Fix: allow totalMessageLimit to be None in MessageQueueProcessor

- CHANGELOG.md
- core/queues/message_queue_processor.py
> Feature: Update MessageQueueProcessor to allow batch processing in parallel

- CHANGELOG.md
- core/queues/__init__.py
- core/queues/model.py
- core/queues/sqs_message_queue.py
> Adding postDate to message

- CHANGELOG.md
- core/web3/eth_client.py
> Feature: allow downloading a block with transaction data in EthClient

- CHANGELOG.md
- core/web3/eth_client.py
> Feature: Updated RestEthClient to throw BadRequestException for malformed responses

- CHANGELOG.md
- core/web3/eth_client.py
- setup.py
> Feature: Update RestEthClient to throw BadRequestException for empty responses

- CHANGELOG.md
- core/queues/sqs_message_queue.py
> KIBA-1339: Add send_messages to SqsMessageQueue

- CHANGELOG.md
- core/requester.py
- core/store/database.py
- core/store/retriever.py
- core/store/saver.py
- core/web3/eth_client.py
- requirements-dev.txt
- requirements.txt
- setup.py
> ENG-1363: Replace databases with sqlalchemy

- CHANGELOG.md
- core/requester.py
> Feature: update Requester to follow redirects by default

- CHANGELOG.md
- core/s3_manager.py
- core/web3/eth_client.py
- requirements-dev.txt
- setup.py
> Feature: replace boto3 with aiobotocore for S3Manager

- CHANGELOG.md
- core/queues/sqs_message_queue.py
- core/s3_manager.py
- requirements-dev.txt
- setup.py
> Feature: replace boto3 with aiobotocore for SqsMessageQueue

- CHANGELOG.md
- core/api/database_connection_middleware.py
- core/store/database.py
> Featutre: Added DatabaseConnectionMiddleware to manage api database connections

- CHANGELOG.md
- core/api/database_connection_middleware.py
- core/logging.py
- core/queues/message_queue_processor.py
- core/requester.py
- core/s3_manager.py
- core/store/saver.py
- core/util/value_holder.py
- core/web3/eth_client.py
> KIBA-1362: Add logging module

- CHANGELOG.md
- core/api/middleware/logging_middleware.py
- core/queues/message_queue_processor.py
> Feature: add requestIdHolder to MessageQueueProcessor

- core/logging.py
> Feature: add json logging

- core/logging.py
> Feature: update logging date format

- core/logging.py
> Feature: update json logging formatter to use ints and floats

- core/store/saver.py
> Fix: correct saving for when there is no connection

- CHANGELOG.md
- core/aws_requester.py
- core/requester.py
> Feature: Added formFiles to Requester.post_form and Requester.make_request

- core/s3_manager.py
> Fiddle: update S3Manager to use more efficient check_file_exists with a response

- CHANGELOG.md
- core/s3_manager.py
> Feature: added head_file to S3Manager

- CHANGELOG.md
- core/api/middleware/database_connection_middleware.py
> Feature: only create db transactions for non-GET requests

- CHANGELOG.md
- core/requester.py
- core/util/date_util.py
> Feature: added dateUtil functions

- core/aws_requester.py
- core/logging.py
- core/queues/message_queue_processor.py
- core/util/dict_util.py
- core/util/list_util.py
- core/util/value_holder.py
- requirements-dev.txt
- requirements.txt
- setup.py
> Fiddle: update dependencies

- .github/workflows/release.yml
- CHANGELOG.md
- core/api/middleware/exception_handling_middleware.py
- core/exceptions.py
> Feature: Added shouldAddCacheHeader to relevant RedirectExceptions

- CHANGELOG.md
- core/exceptions.py
- core/requester.py
- core/store/saver.py
- core/util/date_util.py
> Feature: Updated Saver to throw SavingException when saving fails

- CHANGELOG.md
- core/queues/message_queue_processor.py
- core/queues/model.py
- core/queues/sqs_message_queue.py
> Feature: Update MessageNeedsReprocessingException to support rescheduling a message

- core/queues/message_queue_processor.py
- core/queues/sqs_message_queue.py
> Fix: pass delaySeconds correctly into MessageQueue

- CHANGELOG.md
- core/requester.py
> Feature: Use www-authenticate as message (if available) in 401 responses

- .github/workflows/pull-request.yml
- Dockerfile
- core/api/middleware/exception_handling_middleware.py
- core/api/middleware/logging_middleware.py
- core/api/middleware/server_headers_middleware.py
- core/aws_requester.py
- core/logging.py
- core/queues/message_queue_processor.py
- core/queues/model.py
- core/queues/sqs_message_queue.py
- core/requester.py
- core/s3_manager.py
- core/store/database.py
- core/store/retriever.py
- core/store/saver.py
- core/util/dict_util.py
- core/util/list_util.py
- core/util/value_holder.py
- core/web3/eth_client.py
- requirements-dev.txt
- requirements.txt
- setup.py
> Fiddle: update to use typing and security checks

- setup.py
> Fiddle: add database-types extra to setup.py

- core/queues/sqs_message_queue.py
- core/requester.py
- core/store/database.py
- core/store/retriever.py
- core/store/saver.py
- requirements-dev.txt
- setup.py
> Fiddle: improve types + update to sqlalchemy2

- CHANGELOG.md
- core/queues/message_queue_processor.py
- core/queues/model.py
- requirements-dev.txt
- setup.py
> Fix: correct type for sqs message

- CHANGELOG.md
- core/web3/eth_client.py
- requirements-dev.txt
> Feature: Added call_contract_function to EthClientInterface

- .github/workflows/pull-request.yml
- CHANGELOG.md
- Dockerfile
- core/store/saver.py
- makefile
> Feature: added _insert_record, _update_records, and _delete_records to Saver 

- core/store/saver.py
- requirements-dev.txt
- setup.py
> Fix: correct typing for new saver functions

- CHANGELOG.md
- core/store/retriever.py
> Feature: added BooleanFieldFilter to Retriever

- CHANGELOG.md
- core/requester.py
> Fix: Update Requester to send date correctly for PUT requests

- CHANGELOG.md
- core/requester.py
> Fiddle: update Requester to have patch_json function

- CHANGELOG.md
- core/discord_client.py
- core/notification_client.py
- core/queues/message_queue_processor.py
- core/slack_client.py
- core/util/date_util.py
> Feature: add calculate_diff_days and calculate_diff_years to date_util

- CHANGELOG.md
- core/util/date_util.py
> Feature: added datetime_to_utc to date_util

- core/queues/model.py
- requirements.txt
> Fix: corrections for new pydantic

- core/queues/model.py
- core/service_client.py
> Fix: more updates for pydantic

- .github/workflows/deploy.yml
- .github/workflows/pull-request.yml
- .github/workflows/release.yml
- CHANGELOG.md
- core/logging.py
> Fiddle: added init_external_loggers to logging

- core/util/typing_util.py
- requirements-dev.txt
> Fiddle: update JsonDict and JsonList type to be precise

- core/queues/aqs.py
- core/s3_manager.py
- core/util/typing_util.py
- requirements-dev.txt
- requirements.txt
- setup.py
> Fiddle: reset json definitions to old definition

- CHANGELOG.md
- core/util/date_util.py
> Feature: add end_of_day to date_util

- CHANGELOG.md
- core/store/database.py
- requirements-dev.txt
> Added SQLite database connection

- CHANGELOG.md
- core/api/api_request.py
- core/api/api_respnse.py
- core/api/authorizer.py
- core/api/default_routes.py
- core/api/json_route.py
- core/api/middleware/exception_handling_middleware.py
- core/http/jwt.py
- core/http/rest_method.py
- core/store/database.py
- requirements.txt
- setup.py
> Feature: add core-api that uses starlette only

- core/api/json_route.py
> Fix: add queryParams to json_route

- core/api/json_route.py
> Fiddle: update validation error message thrown by json_route

- requirements-dev.txt
- setup.py
> Fiddle: update asyncpg version

- core/web3/eth_client.py
> Fix: correction for latest web3

- setup.py
> Fix: correct setup.py for uvicorn version

- CHANGELOG.md
- core/web3/eth_client.py
> Feature: update RestEthClient with new functions

- core/web3/eth_client.py
> Feature: Added raiseOnFailure to RestEthClient.wait_for_transaction_receipt

- CHANGELOG.md
- core/caching/dict_cache.py
- core/caching/file_cache.py
- core/util/date_util.py
- tests/util/test_date_util.py
> Fix: remove locking from caches

- core/util/date_util.py
- tests/util/test_date_util.py
> Fiddle: add back dte_util.datetime_to_utc

- CHANGELOG.md
- Dockerfile
- core/api/json_route.py
- core/aws_requester.py
- core/exceptions.py
- core/http/jwt.py
- core/logging.py
- core/requester/requester.py
- core/service_client.py
- core/util/json_util.py
- core/util/typing_util.py
- core/web3/eth_client.py
- pyproject.toml
- tests/util/test_json_util.py
> Feature: add json_util

- core/api/middleware/database_connection_middleware.py
- core/store/database.py
- pyproject.toml
- uv.lock
> Fix: make database connection always required

- core/util/json_util.py
> Fiddle: fix for json encoding

- core/web3/eth_client.py
> Fiddle: implement EthClient.fill_transaction_params

- core/caching/file_cache.py
- core/util/date_util.py
- tests/caching/test_file_cache.py
- tests/util/test_date_util.py
> Fiddle: small updates for fileCache and dateUtil

- core/util/file_util.py
- tests/util/test_file_util.py
> Feature: ignore missing files when removing

- .github/workflows/pull-request.yml
- makefile
- pyproject.toml
- tests/util/test_date_util.py
- uv.lock
> Fiddle: use build-py to run tests

- core/web3/eth_client.py
> Fix: make blockNumber hex in ethClient

- CHANGELOG.md
- core/web3/eth_client.py
- tests/web3/test_rest_eth_client.py
> Fiddle: add maxWaitSeconds to EthClient.wait_for_transaction + Add RestEthClient tests

- CHANGELOG.md
- core/api/api_request.py
- core/api/authorizer.py
- core/api/json_route.py
- core/api/middleware/exception_handling_middleware.py
- core/api/streaming_json_route.py
- core/queues/aqs.py
- core/queues/message_queue.py
- core/queues/message_queue_processor.py
- core/requester/requester.py
- core/util/async_util.py
- core/util/dict_util.py
- core/util/list_util.py
- core/util/value_holder.py
- core/web3/eth_client.py
- pyproject.toml
- tests/util/test_async_util.py
- uv.lock
> Fiddle: add async_util.gather_batched + update dependencies
